// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type GalleryDocumentDataSlicesSlice = GalleryImagesSlice;

/**
 * Content for Gallery documents
 */
interface GalleryDocumentData {
  /**
   * Slice Zone field in *Gallery*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<GalleryDocumentDataSlicesSlice> /**
   * Meta Title field in *Gallery*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: gallery.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Gallery*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: gallery.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Gallery*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Gallery document from Prismic
 *
 * - **API ID**: `gallery`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type GalleryDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<GalleryDocumentData>,
    "gallery",
    Lang
  >;

type ProjectPageDocumentDataSlicesSlice =
  | EmbedMapSlice
  | ProjectIntroSlice
  | ProjectHeroSlice;

/**
 * Content for Project page documents
 */
interface ProjectPageDocumentData {
  /**
   * Slice Zone field in *Project page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: project_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ProjectPageDocumentDataSlicesSlice> /**
   * Meta Title field in *Project page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: project_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Project page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: project_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Project page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Project page document from Prismic
 *
 * - **API ID**: `project_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProjectPageDocumentData>,
    "project_page",
    Lang
  >;

export type AllDocumentTypes = GalleryDocument | ProjectPageDocument;

/**
 * Primary content in *EmbedMap → Default → Primary*
 */
export interface EmbedMapSliceDefaultPrimary {
  /**
   * iframecode field in *EmbedMap → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: embed_map.default.primary.iframecode
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  iframecode: prismic.RichTextField;
}

/**
 * Default variation for EmbedMap Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EmbedMapSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<EmbedMapSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *EmbedMap*
 */
type EmbedMapSliceVariation = EmbedMapSliceDefault;

/**
 * EmbedMap Shared Slice
 *
 * - **API ID**: `embed_map`
 * - **Description**: EmbedMap
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EmbedMapSlice = prismic.SharedSlice<
  "embed_map",
  EmbedMapSliceVariation
>;

/**
 * Item in *GalleryImages → Default → Primary → Gallery Image*
 */
export interface GalleryImagesSliceDefaultPrimaryGalleryImageItem {
  /**
   * image field in *GalleryImages → Default → Primary → Gallery Image*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery_images.default.primary.gallery_image[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *GalleryImages → Default → Primary*
 */
export interface GalleryImagesSliceDefaultPrimary {
  /**
   * Gallery Image field in *GalleryImages → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery_images.default.primary.gallery_image[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  gallery_image: prismic.GroupField<
    Simplify<GalleryImagesSliceDefaultPrimaryGalleryImageItem>
  >;
}

/**
 * Default variation for GalleryImages Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GalleryImagesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<GalleryImagesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *GalleryImages*
 */
type GalleryImagesSliceVariation = GalleryImagesSliceDefault;

/**
 * GalleryImages Shared Slice
 *
 * - **API ID**: `gallery_images`
 * - **Description**: GalleryImages
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GalleryImagesSlice = prismic.SharedSlice<
  "gallery_images",
  GalleryImagesSliceVariation
>;

/**
 * Item in *ProjectHero → Default → Primary → Project Tags*
 */
export interface ProjectHeroSliceDefaultPrimaryProjectTagsItem {
  /**
   * Title field in *ProjectHero → Default → Primary → Project Tags*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_hero.default.primary.project_tags[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Tag field in *ProjectHero → Default → Primary → Project Tags*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_hero.default.primary.project_tags[].tag
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tag: prismic.KeyTextField;
}

/**
 * Primary content in *ProjectHero → Default → Primary*
 */
export interface ProjectHeroSliceDefaultPrimary {
  /**
   * Project Title field in *ProjectHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_hero.default.primary.project_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  project_title: prismic.KeyTextField;

  /**
   * Caption field in *ProjectHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_hero.default.primary.caption
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  caption: prismic.KeyTextField;

  /**
   * Project Hero Image field in *ProjectHero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_hero.default.primary.project_hero_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  project_hero_image: prismic.ImageField<never>;

  /**
   * Project Tags field in *ProjectHero → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: project_hero.default.primary.project_tags[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  project_tags: prismic.GroupField<
    Simplify<ProjectHeroSliceDefaultPrimaryProjectTagsItem>
  >;

  /**
   * Color field in *ProjectHero → Default → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: project_hero.default.primary.color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  color: prismic.ColorField;
}

/**
 * Default variation for ProjectHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectHeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectHeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProjectHero*
 */
type ProjectHeroSliceVariation = ProjectHeroSliceDefault;

/**
 * ProjectHero Shared Slice
 *
 * - **API ID**: `project_hero`
 * - **Description**: ProjectHero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectHeroSlice = prismic.SharedSlice<
  "project_hero",
  ProjectHeroSliceVariation
>;

/**
 * Item in *ProjectIntro → Default → Primary → Project Images*
 */
export interface ProjectIntroSliceDefaultPrimaryProjectImagesItem {
  /**
   * Project Image field in *ProjectIntro → Default → Primary → Project Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_intro.default.primary.project_images[].project_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  project_image: prismic.ImageField<never>;
}

/**
 * Item in *ProjectIntro → Default → Primary → Features*
 */
export interface ProjectIntroSliceDefaultPrimaryFeaturesItem {
  /**
   * Feature Title field in *ProjectIntro → Default → Primary → Features*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_intro.default.primary.features[].feature_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  feature_title: prismic.KeyTextField;

  /**
   * Feature Detail field in *ProjectIntro → Default → Primary → Features*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_intro.default.primary.features[].feature_detail
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  feature_detail: prismic.KeyTextField;
}

/**
 * Primary content in *ProjectIntro → Default → Primary*
 */
export interface ProjectIntroSliceDefaultPrimary {
  /**
   * Intro Para one field in *ProjectIntro → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_intro.default.primary.intro_para_one
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  intro_para_one: prismic.KeyTextField;

  /**
   * Intro Para two field in *ProjectIntro → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_intro.default.primary.intro_para_two
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  intro_para_two: prismic.KeyTextField;

  /**
   * Portrait Image One field in *ProjectIntro → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_intro.default.primary.portrait_image_one
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  portrait_image_one: prismic.ImageField<never>;

  /**
   * Project Images field in *ProjectIntro → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: project_intro.default.primary.project_images[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  project_images: prismic.GroupField<
    Simplify<ProjectIntroSliceDefaultPrimaryProjectImagesItem>
  >;

  /**
   * Features field in *ProjectIntro → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: project_intro.default.primary.features[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  features: prismic.GroupField<
    Simplify<ProjectIntroSliceDefaultPrimaryFeaturesItem>
  >;

  /**
   * Next Project Link field in *ProjectIntro → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: project_intro.default.primary.next_project_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  next_project_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Previous Project Link field in *ProjectIntro → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: project_intro.default.primary.previous_project_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  previous_project_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Color field in *ProjectIntro → Default → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: project_intro.default.primary.color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  color: prismic.ColorField;

  /**
   * Video Link field in *ProjectIntro → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: project_intro.default.primary.video_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  video_link: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * Project Vision field in *ProjectIntro → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_intro.default.primary.project_vision
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  project_vision: prismic.RichTextField;

  /**
   * Google Map field in *ProjectIntro → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: project_intro.default.primary.google_map
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  google_map: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Brochure field in *ProjectIntro → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: project_intro.default.primary.brochure
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  brochure: prismic.LinkToMediaField<prismic.FieldState, never>;
}

/**
 * Default variation for ProjectIntro Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectIntroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectIntroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProjectIntro*
 */
type ProjectIntroSliceVariation = ProjectIntroSliceDefault;

/**
 * ProjectIntro Shared Slice
 *
 * - **API ID**: `project_intro`
 * - **Description**: ProjectIntro
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectIntroSlice = prismic.SharedSlice<
  "project_intro",
  ProjectIntroSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      GalleryDocument,
      GalleryDocumentData,
      GalleryDocumentDataSlicesSlice,
      ProjectPageDocument,
      ProjectPageDocumentData,
      ProjectPageDocumentDataSlicesSlice,
      AllDocumentTypes,
      EmbedMapSlice,
      EmbedMapSliceDefaultPrimary,
      EmbedMapSliceVariation,
      EmbedMapSliceDefault,
      GalleryImagesSlice,
      GalleryImagesSliceDefaultPrimaryGalleryImageItem,
      GalleryImagesSliceDefaultPrimary,
      GalleryImagesSliceVariation,
      GalleryImagesSliceDefault,
      ProjectHeroSlice,
      ProjectHeroSliceDefaultPrimaryProjectTagsItem,
      ProjectHeroSliceDefaultPrimary,
      ProjectHeroSliceVariation,
      ProjectHeroSliceDefault,
      ProjectIntroSlice,
      ProjectIntroSliceDefaultPrimaryProjectImagesItem,
      ProjectIntroSliceDefaultPrimaryFeaturesItem,
      ProjectIntroSliceDefaultPrimary,
      ProjectIntroSliceVariation,
      ProjectIntroSliceDefault,
    };
  }
}
