// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  embed_map: defineAsyncComponent(() => import("./EmbedMap/index.vue")),
  gallery_images: defineAsyncComponent(
    () => import("./GalleryImages/index.vue"),
  ),
  project_hero: defineAsyncComponent(() => import("./ProjectHero/index.vue")),
  project_intro: defineAsyncComponent(() => import("./ProjectIntro/index.vue")),
});
